In [30]:
# ==========================================================
# Customer Churn Prediction
# Notebook 1: Data Cleaning
# ==========================================================
#
# Objective:
# Prepare the IBM Telco Customer Churn dataset for machine
# learning by handling missing values, removing unnecessary
# features, correcting data types, and producing a clean
# dataset for analysis.
#
# Dataset:
# IBM Telco Customer Churn Dataset
#
# Output:
# customer_churn_cleaned.xlsx
# ==========================================================

In [29]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("Telco_customer_churn.xlsx")

In [3]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [4]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

In [6]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [7]:
df.describe(include="object")

,CustomerID,Country,State,City,Lat Long,Gender,Senior Citizen,Partner,Dependents,Phone Service,...,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Total Charges,Churn Label,Churn Reason
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,...,7043,7043,7043,7043,7043,7043,7043,7043.0,7043,1869
unique,7043,1,1,1129,1652,2,2,2,2,2,...,3,3,3,3,3,2,4,6531.0,2,20
top,3668-QPYBK,United States,California,Los Angeles,"33.964131, -118.272783",Male,No,No,No,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,20.2,No,Attitude of support person
freq,1,7043,7043,305,5,3555,5901,3641,5416,6361,...,3095,3473,2810,2785,3875,4171,2365,11.0,5174,192

In [8]:
df["Count"].value_counts()

Count
1    7043
Name: count, dtype: int64

In [9]:
df["Churn Label"].value_counts()

Churn Label
No     5174
Yes    1869
Name: count, dtype: int64

In [10]:
df["Churn Value"].value_counts()

Churn Value
0    5174
1    1869
Name: count, dtype: int64

In [11]:
df[["Churn Label", "Churn Value"]].head(10)

  Churn Label  Churn Value
0         Yes            1
1         Yes            1
2         Yes            1
3         Yes            1
4         Yes            1
5         Yes            1
6         Yes            1
7         Yes            1
8         Yes            1
9         Yes            1

In [12]:
df["Total Charges"].head(20)

0      108.15
1      151.65
2       820.5
3     3046.05
4      5036.3
5      528.35
6       39.65
7       20.15
8     4749.15
9        30.2
10     1093.1
11      316.9
12    3549.25
13     1105.4
14     144.15
15     1426.4
16      633.3
17    1752.55
18     857.25
19      79.35
Name: Total Charges, dtype: object

In [13]:
df["Total Charges"].tail(20)

7023    1020.75
7024        826
7025        239
7026     7544.3
7027     6479.4
7028    3626.35
7029     1679.4
7030     931.55
7031    4326.25
7032     263.05
7033      39.25
7034     3316.1
7035    2625.25
7036     1495.1
7037      743.3
7038     1419.4
7039     1990.5
7040     7362.9
7041     346.45
7042     6844.5
Name: Total Charges, dtype: object

In [14]:
df[df["Total Charges"] == " "]

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
2234,4472-LVYGI,1,United States,California,San Bernardino,92408,"34.084909, -117.258107",34.084909,-117.258107,Female,...,Two year,Yes,Bank transfer (automatic),52.55,,No,0,36,2578,NaN
2438,3115-CZMZD,1,United States,California,Independence,93526,"36.869584, -118.189241",36.869584,-118.189241,Male,...,Two year,No,Mailed check,20.25,,No,0,68,5504,NaN
2568,5709-LVOEQ,1,United States,California,San Mateo,94401,"37.590421, -122.306467",37.590421,-122.306467,Female,...,Two year,No,Mailed check,80.85,,No,0,45,2048,NaN
2667,4367-NUYAO,1,United States,California,Cupertino,95014,"37.306612, -122.080621",37.306612,-122.080621,Male,...,Two year,No,Mailed check,25.75,,No,0,48,4950,NaN
2856,1371-DWPAZ,1,United States,California,Redcrest,95569,"40.363446, -123.835041",40.363446,-123.835041,Female,...,Two year,No,Credit card (automatic),56.05,,No,0,30,4740,NaN
4331,7644-OMVMY,1,United States,California,Los Angeles,90029,"34.089953, -118.294824",34.089953,-118.294824,Male,...,Two year,No,Mailed check,19.85,,No,0,53,2019,NaN
4687,3213-VVOLG,1,United States,California,Sun City,92585,"33.739412, -117.173334",33.739412,-117.173334,Male,...,Two year,No,Mailed check,25.35,,No,0,49,2299,NaN
5104,2520-SGTTA,1,United States,California,Ben Lomond,95005,"37.078873, -122.090386",37.078873,-122.090386,Female,...,Two year,No,Mailed check,20.00,,No,0,27,3763,NaN
5719,2923-ARZLG,1,United States,California,La Verne,91750,"34.144703, -117.770299",34.144703,-117.770299,Male,...,One year,Yes,Mailed check,19.70,,No,0,69,4890,NaN
6772,4075-WKNIU,1,United States,California,Bell,90201,"33.970343, -118.171368",33.970343,-118.171368,Female,...,Two year,No,Mailed check,73.35,,No,0,44,2342,NaN
6840,2775-SEFEE,1,United States,California,Wilmington,90744,"33.782068, -118.262263",33.782068,-118.262263,Male,...,Two year,Yes,Bank transfer (automatic),61.90,,No,0,65,5188,NaN

In [15]:
df["Country"].value_counts()

Country
United States    7043
Name: count, dtype: int64

In [16]:
df["State"].value_counts()

State
California    7043
Name: count, dtype: int64

In [17]:
df["Senior Citizen"].value_counts()

Senior Citizen
No     5901
Yes    1142
Name: count, dtype: int64

In [18]:
df[["Churn Score", "Churn Value"]].describe()

       Churn Score  Churn Value
count  7043.000000  7043.000000
mean     58.699418     0.265370
std      21.525131     0.441561
min       5.000000     0.000000
25%      40.000000     0.000000
50%      61.000000     0.000000
75%      75.000000     1.000000
max     100.000000     1.000000

In [19]:
df.groupby("Churn Value")["Churn Score"].describe()

              count       mean        std   min   25%   50%   75%    max
Churn Value
0            5174.0  50.098183  17.702277   5.0  35.0  50.0  66.0   80.0
1            1869.0  82.510433  10.328570  65.0  74.0  82.0  91.0  100.0

In [20]:
df.groupby("Churn Value")["CLTV"].describe()

,count,mean,std,min,25%,50%,75%,max
Churn Value,,,,,,,,
0,5174.0,4490.921337,1167.703198,2003.0,3643.75,4620.0,5434.75,6500.0
1,1869.0,4149.414660,1189.370707,2003.0,3101.00,4238.0,5166.00,6484.0

In [21]:
## Feature Note

# The CLTV feature was retained because the dataset documentation states that it is a predicted Customer Lifetime Value derived from existing customer data. Since it represents a business metric that companies commonly compute before customer churn occurs, it is treated as an available feature rather than data leakage.

In [22]:
df["Total Charges"] = pd.to_numeric(
    df["Total Charges"],
    errors="coerce"
)

In [23]:
df["Total Charges"] = df["Total Charges"].fillna(0)

In [24]:
df["Total Charges"].isnull().sum()

0

In [25]:
columns_to_drop = [
    "CustomerID",
    "Count",
    "Country",
    "State",
    "Churn Label",
    "Churn Reason",
    "Churn Score"
]

df = df.drop(columns=columns_to_drop)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7043 non-null   object
 1   Zip Code           7043 non-null   int64
 2   Lat Long           7043 non-null   object
 3   Latitude           7043 non-null   float64
 4   Longitude          7043 non-null   float64
 5   Gender             7043 non-null   object
 6   Senior Citizen     7043 non-null   object
 7   Partner            7043 non-null   object
 8   Dependents         7043 non-null   object
 9   Tenure Months      7043 non-null   int64
 10  Phone Service      7043 non-null   object
 11  Multiple Lines     7043 non-null   object
 12  Internet Service   7043 non-null   object
 13  Online Security    7043 non-null   object
 14  Online Backup      7043 non-null   object
 15  Device Protection  7043 non-null   object
 16  Tech Support       7043 non-null   object
 17  Streaming TV       7043 non-null   object
 18  Streaming Movies   7043 non-null   object
 19  Contract           7043 non-null   object
 20  Paperless Billing  7043 non-null   object
 21  Payment Method     7043 non-null   object
 22  Monthly Charges    7043 non-null   float64
 23  Total Charges      7043 non-null   float64
 24  Churn Value        7043 non-null   int64
 25  CLTV               7043 non-null   int64
dtypes: float64(4), int64(4), object(18)
memory usage: 1.4+ MB

In [27]:
df.to_excel(
    "Telco Customer Churn Cleaned.xlsx",
    index=False
)

In [31]:
# ==========================================================
# Data Cleaning Summary
# ==========================================================
#
# The dataset was successfully cleaned and prepared foranalysis. Missing values were handled, unnecessary columns
# were removed, data types were corrected, and the cleaned dataset was exported for use in the EDA and modeling stages.
# ==========================================================